<a href="https://colab.research.google.com/github/priyadarshpv/Weather_classification_prediction/blob/main/Weather_classification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df=pd.read_csv('/content/drive/MyDrive/data sets/weather_classification_data.csv')

In [ ]:
df

,Temperature,Humidity,Wind Speed,Precipitation (%),Cloud Cover,Atmospheric Pressure,UV Index,Season,Visibility (km),Location,Weather Type
0,14.0,73,9.5,82.0,partly cloudy,1010.82,2,Winter,3.5,inland,Rainy
1,39.0,96,8.5,71.0,partly cloudy,1011.43,7,Spring,10.0,inland,Cloudy
2,30.0,64,7.0,16.0,clear,1018.72,5,Spring,5.5,mountain,Sunny
3,38.0,83,1.5,82.0,clear,1026.25,7,Spring,1.0,coastal,Sunny
4,27.0,74,17.0,66.0,overcast,990.67,1,Winter,2.5,mountain,Rainy
...,...,...,...,...,...,...,...,...,...,...,...
13195,10.0,74,14.5,71.0,overcast,1003.15,1,Summer,1.0,mountain,Rainy
13196,-1.0,76,3.5,23.0,cloudy,1067.23,1,Winter,6.0,coastal,Snowy
13197,30.0,77,5.5,28.0,overcast,1012.69,3,Autumn,9.0,coastal,Cloudy
13198,3.0,76,10.0,94.0,overcast,984.27,0,Winter,2.0,inland,Snowy
13199,-5.0,38,0.0,92.0,overcast,1015.37,5,Autumn,10.0,mountain,Rainy

In [ ]:
df.isna().sum()

Temperature             0
Humidity                0
Wind Speed              0
Precipitation (%)       0
Cloud Cover             0
Atmospheric Pressure    0
UV Index                0
Season                  0
Visibility (km)         0
Location                0
Weather Type            0
dtype: int64

In [ ]:
df.duplicated().sum()

0

In [ ]:
df['Weather Type'].value_counts()

Weather Type
Rainy     3300
Cloudy    3300
Sunny     3300
Snowy     3300
Name: count, dtype: int64

In [ ]:
df['Cloud Cover'].value_counts()

Cloud Cover
overcast         6090
partly cloudy    4560
clear            2139
cloudy            411
Name: count, dtype: int64

In [ ]:
df['Season'].value_counts()

Season
Winter    5610
Spring    2598
Autumn    2500
Summer    2492
Name: count, dtype: int64

In [ ]:
df['Location'].value_counts()

Location
inland      4816
mountain    4813
coastal     3571
Name: count, dtype: int64

In [ ]:
from sklearn.preprocessing import LabelEncoder
weathertype=LabelEncoder()
df['Weather Type']=weathertype.fit_transform(df['Weather Type'])

In [ ]:
from sklearn.preprocessing import OneHotEncoder
onehot=OneHotEncoder(sparse_output=False,drop='first')
res=onehot.fit_transform(df[['Cloud Cover','Season','Location']])
df=df.drop(columns=['Cloud Cover','Season','Location'])

In [ ]:
res=pd.DataFrame(res)
res.columns=res.columns.astype(str)

In [ ]:
df=df.join(res)

In [ ]:
X=df.drop(columns='Weather Type')
y=df['Weather Type']

In [ ]:
from sklearn.preprocessing import MinMaxScaler
minmax=MinMaxScaler()
x_scaled=minmax.fit_transform(X)

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x_scaled,y,test_size=0.2,random_state=42)

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import classification_report

In [ ]:
models=[KNeighborsClassifier(),SVC(),GaussianNB()]
for model in models:
  print(model)
  model.fit(x_train,y_train)
  y_pred=model.predict(x_test)
  print(classification_report(y_test,y_pred))
  print('------------------------------------------')

KNeighborsClassifier()
              precision    recall  f1-score   support

           0       0.83      0.88      0.85       651
           1       0.85      0.86      0.85       647
           2       0.94      0.94      0.94       701
           3       0.94      0.88      0.91       641

    accuracy                           0.89      2640
   macro avg       0.89      0.89      0.89      2640
weighted avg       0.89      0.89      0.89      2640

------------------------------------------
SVC()
              precision    recall  f1-score   support

           0       0.83      0.88      0.85       651
           1       0.88      0.86      0.87       647
           2       0.92      0.94      0.93       701
           3       0.92      0.88      0.90       641

    accuracy                           0.89      2640
   macro avg       0.89      0.89      0.89      2640
weighted avg       0.89      0.89      0.89      2640

------------------------------------------
GaussianNB()
              precision    recall  f1-score   support

           0       0.89      0.78      0.83       651
           1       0.80      0.73      0.76       647
           2       0.82      0.94      0.88       701
           3       0.84      0.89      0.86       641

    accuracy                           0.84      2640
   macro avg       0.84      0.83      0.83      2640
weighted avg       0.84      0.84      0.84      2640

------------------------------------------

In [ ]:
df.sample(1)

,Temperature,Humidity,Wind Speed,Precipitation (%),Atmospheric Pressure,UV Index,Visibility (km),Weather Type,0,1,2,3,4,5,6,7
3557,27.0,66,8.5,23.0,1017.97,4,7.5,0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0

In [ ]:
#14.0	73	9.5	82.0	partly cloudy	1010.82	2	Winter	3.5	inland
x1=[['partly cloudy','Winter','inland']]
x11=onehot.transform(x1)
x2=[[14.0,73,9.5,82.0,1010.82,2,3.5]]
xx=np.hstack([x2,x11])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(

In [ ]:
xx_scaled=minmax.transform(xx)

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but MinMaxScaler was fitted with feature names
  warnings.warn(

In [ ]:
model.predict(xx_scaled)

array([2])

In [ ]:
weathertype.inverse_transform([2])

array(['Snowy'], dtype=object)

In [ ]:
#39.0	96	8.5	71.0	partly cloudy	1011.43	7	Spring	10.0	inland	Cloudy
x1=[['partly cloudy','Spring','inland']]
x11=onehot.transform(x1)
x2=[[39.0,	96	,8.5	,71.0,	1011.43,	7	,	10.0]]
xx=np.hstack([x2,x11])
xx_scaled=minmax.transform(xx)
s=model.predict(xx_scaled)
weathertype.inverse_transform([s])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but MinMaxScaler was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_label.py:153: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

array(['Sunny'], dtype=object)

In [ ]:
#30.0	77	5.5	28.0	overcast	1012.69	3	Autumn	9.0	coastal
x1=[['overcast','Autumn','coastal']]
x11=onehot.transform(x1)
x2=[[30.0,	77	,5.5,	28.0	,	1012.69	,3,	9.0]]
xx=np.hstack([x2,x11])
xx_scaled=minmax.transform(xx)
s=model.predict(xx_scaled)
weathertype.inverse_transform([s])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but MinMaxScaler was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_label.py:153: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

array(['Cloudy'], dtype=object)

In [ ]:
df

,Temperature,Humidity,Wind Speed,Precipitation (%),Atmospheric Pressure,UV Index,Visibility (km),Weather Type,0,1,2,3,4,5,6,7
0,14.0,73,9.5,82.0,1010.82,2,3.5,1,0.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0
1,39.0,96,8.5,71.0,1011.43,7,10.0,0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0
2,30.0,64,7.0,16.0,1018.72,5,5.5,3,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
3,38.0,83,1.5,82.0,1026.25,7,1.0,3,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
4,27.0,74,17.0,66.0,990.67,1,2.5,1,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13195,10.0,74,14.5,71.0,1003.15,1,1.0,1,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0
13196,-1.0,76,3.5,23.0,1067.23,1,6.0,2,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
13197,30.0,77,5.5,28.0,1012.69,3,9.0,0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
13198,3.0,76,10.0,94.0,984.27,0,2.0,2,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0
13199,-5.0,38,0.0,92.0,1015.37,5,10.0,1,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0

In [ ]:
def weatherprediction():
  Temperature=int(input('enter tempreture'))
  Humidity=int(input('enter Humidity'))
  wind_speed=int(input('enter wind_speed'))
  Percipitation=int(input('enter Percipitation'))
  Atmosphere_pressure=int(input('enter Atmospheric Pressure'))
  UVindex=int(input('enter UV index'))
  Visibility=int(input('enter Visibility'))
  cloud=input('enter Cloud cover(overcast,partly,cloudy,clear,cloudy)')
  season=input('enter season(Winter,Spring,Autumn,Summer)')
  location=input('enter location(inland,mountain,coastal)')

  num=np.array([[Temperature,Humidity,wind_speed,Percipitation,Atmosphere_pressure,UVindex,Visibility]])
  var=np.array([[cloud,season,location]])

  x=onehot.transform(var)
  xx=np.hstack([num,x])
  xx_scaled=minmax.transform(xx)
  s=model.predict(xx_scaled)
  return weathertype.inverse_transform(s)


print(weatherprediction())

enter tempreture30
enter Humidity30
enter wind_speed43
enter Percipitation32
enter Atmospheric Pressure232
enter UV index3
enter Visibility5
enter Cloud cover(overcast,partly,cloudy,clear,cloudy)overcast
enter season(Winter,Spring,Autumn,Summer)Summer
enter location(inland,mountain,coastal)coastal
['Rainy']

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but MinMaxScaler was fitted with feature names
  warnings.warn(